cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    kame:
      email: ishigame@ykaa.jp
      name: TakashiIshigame
      password: $2b$12$KgBHVo4I7libn.eFOyoeme9wsuOov7i0S82/vm7VgmaNv7CSI1rna
